### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by Xiong5Heng** [dongdongbh/RCQL#1]
when I run the main.py, I got below error

line 178, in update_rotate
    rotate_mask[i] = rotate.squeeze(-1).eq(i)
NameError: name 'rotate_mask' is not defined

**Comment by Xiong5Heng** [comment]
您好，最新commit之后依旧是那个function会出现问题：
line 210, in update_rotate
    box_l_rotate[i] = torch.masked_select(box_l_rotate[i], rotate_mask[i])
RuntimeError: The expanded size of the tensor (128) must match the existing size (11) at non-singleton dimension 0.  Target sizes: [128].  Tensor sizes: [11]

**Comment by dongdongbh** [comment]
Fixed, please try the last commit

**Comment by dongdongbh** [comment]
close with fixed commits
