### ISSUE TITLE
logger.py的make_output_format函数

### ISSUE THREAD

**Issue by AnhaoZhao-LLMer** [dongdongbh/RCQL#2]
作者您好，请问logger.py里的make_output_format函数返回的都是类的实例化吗？是不是有点问题呢？

**Comment by dongdongbh** [comment]
您好，这个不影响的，它实际上以类的形式内部化了格式，你可以参看_demo函数理解它的原理，实际上在configure函数里面对format类进行了实例化然后作为Logger的属性传入了Logger类，这样一旦配置完成，在外部就不需要考虑format直接用通用接口写log

**Comment by AnhaoZhao-LLMer** [comment]
谢谢您
