### ISSUE TITLE
Simply run main.py with default params, avg_reward get smaller and smaller

### ISSUE THREAD

**Issue by Jetcodery** [dongdongbh/RCQL#3]
----------------------------------
| actor_loss         | 0.0489    |
| alpha_loss         | -29.1     |
| avg_rewards        | 272       |
| entropy            | 3.32      |
| epoch              | 0         |
| explained_variance | -0.000163 |
| gap_ratio          | 0.85      |
| value_loss         | 41.3      |
| var_gap_ratio      | 8.53e-05  |
----------------------------------

...

---------------------------------
| actor_loss         | 0.00868  |
| alpha_loss         | -17.8    |
| avg_rewards        | -21.5    |
| entropy            | 0.358    |
| epoch              | 2.28e+03 |
| explained_variance | 0.883    |
| gap_ratio          | 0.47     |
| value_loss         | 0.0347   |
| var_gap_ratio      | 0.000503 |
---------------------------------

**Comment by dongdongbh** [comment]
Hi, thank you for intersting in our work. As we stated in the paper, 'an entropy maximization strategy is also incorpo-
rated'. Our reward function has two parts, one is the reward related to bin gap, and the other is related to entropy of NN's output. In this way, we encourage the learning algorithm to diversify its output distribution and exploration.

In your results, when the training process continues, the aglorithm goes more centain about its choose, so the entropy part of reward goes smaller, which result in smaller value in total reward. You can see the actual improvement of packing result in the decrease of gap_ratio (from 0.85 to 0.47).

**Comment by Jetcodery** [comment]
hi, may I ask , is there an evaluation function in this Repo? And the test-dataset should be organized like what?
