### ISSUE TITLE
runtimeerror

### ISSUE THREAD

**Issue by AnhaoZhao-LLMer** [dongdongbh/RCQL#4]
您好，我在运行python main.py时遇到了这样的问题RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mask in method wrapper__masked_select)

**Comment by Jetcodery** [comment]
I solved this problem by adding these lines in problems/pack3d/state_pack3d.py

add "from utils.functions import move_to" first,
then add  "rotate_mask = move_to(rotate_mask, 'cuda')" in  class StatePack3D::update_rotate

BTW , i faced another problem which is  the gpu utilization rate  always in low level. @dongdongbh

**Comment by dongdongbh** [comment]
> I solved this problem by adding these lines in problems/pack3d/state_pack3d.py
> 
> add "from utils.functions import move_to" first, then add "rotate_mask = move_to(rotate_mask, 'cuda')" in class StatePack3D::update_rotate
> 
> BTW , i faced another problem which is the gpu utilization rate always in low level. @dongdongbh

The GPU utilization rate depends on batch size, block size, model size, etc.  In my case, I got relatively high GPU utilization rate on 4*2080TI with distributed data parallel mode.

**Comment by dongdongbh** [comment]
nil
