### ISSUE TITLE
使用代码中默认的参数训练2D排样

### ISSUE THREAD

**Issue by Walter0002** [dongdongbh/RCQL#5]
下面是一个排样截图，我用红色圈出来区域y坐标的计算似乎不正确，使用skyline计算y坐标应该不会出现这种情况才对，所以想请教一下！
![image](https://user-images.githubusercontent.com/60635061/205486108-aeeee750-d4f3-432d-8e34-551e42937b08.png)

**Comment by Walter0002** [comment]
另外，对于2D离线排样，StatePack2D.boxes这个成员的含义是当前待排的box吗？为什么在每一步选择box之后，该成员会拼接一个新的box？

**Comment by dongdongbh** [comment]
> 另外，对于2D离线排样，StatePack2D.boxes这个成员的含义是当前待排的box吗？为什么在每一步选择box之后，该成员会拼接一个新的box？

这个问题论文里面有讲，为了实现recurrence，这里的box是FIFO的形式。

**Comment by dongdongbh** [comment]
> 下面是一个排样截图，我用红色圈出来区域y坐标的计算似乎不正确，使用skyline计算y坐标应该不会出现这种情况才对，所以想请教一下！ ![image](https://user-images.githubusercontent.com/60635061/205486108-aeeee750-d4f3-432d-8e34-551e42937b08.png)

这个有些奇怪，似乎是`_get_y_skyline`函数里面mask在前几次更新的时候获取错误导致的，我这边现在没有开发环境，我建议你简单调试一下这部分代码，打印一些值（mask, skyline）看一看（把batch size调小方便调试），这里的逻辑就是检查新来的box的x坐标范围，然后在skyline上对应范围y最大的点作为新box的y起点，加入新的box后更新skyline。 @Phoenixer， 你看看这里是否有问题

**Comment by Darcy0218** [comment]
请问使用colab gpu环境报错如下怎么解决
![image](https://user-images.githubusercontent.com/98735671/211979711-6d4013df-5745-403b-8e21-61ffbfcdd5ac.png)

**Comment by dongdongbh** [comment]
@Walter0002 这个是数据存储类型的问题，你调试一下，应该就把mask对应的变量变成cuda类，可以用例如.to("cuda")之类的方法。
