### ISSUE TITLE
block-num和block-sz分别代表什么呢

### ISSUE THREAD

**Issue by buyaoya** [dongdongbh/RCQL#6]
作者你好，关于代码中，这两个参数的具体含义我搞不清楚，如果一个代表一个例子中一个20个物品进行装箱，那另一个代表什么呢

**Comment by dongdongbh** [comment]
block-sz=20代表模型有20个输入长度，如果要pack更多，根据recurrent模型特性，可以设置更多block-num来实现，例如block-num=10,则有200个boxes需要pack，具体可参考论文中的figure 1.
